### ISSUE TITLE
Broken functionality

### ISSUE THREAD

**Issue by s4kibs4mi** [ava-labs/coreth#148] opened 2021-04-28 09:20 UTC
Version: v0.4.2

```
NewLevelDBDatabaseWithFreezer
```
is broken. It initialises function
```
leveldb.New(file, cache, handles, namespace)
```
but it expects
```
leveldb.New(file, cache, handles, namespace, false) // 5th parameter is missing
```

and in `NewDatabaseWithCache`
```
return &cachingDB{
		db:            trie.NewDatabaseWithCache(db, cache, journal),
		codeSizeCache: csc,
		codeCache:     fastcache.New(codeCacheSize),
	}
```
`trie.NewDatabaseWithCache` is missing

**Comment by s4kibs4mi** [comment] 2021-04-28 16:05
```
go/src/github.com/ava-labs/coreth/core/rawdb/database.go:229:24: not enough arguments in call to "github.com/ethereum/go-ethereum/ethdb/leveldb".New
	have (string, int, int, string)
	want (string, int, int, string, bool)
go/src/github.com/ava-labs/coreth/core/rawdb/database.go:239:26: not enough arguments in call to "github.com/ethereum/go-ethereum/ethdb/leveldb".New
	have (string, int, int, string)
	want (string, int, int, string, bool)
```

**Comment by s4kibs4mi** [comment] 2021-04-28 16:07
@aaronbuchwald

**Comment by aaronbuchwald** [comment] 2021-05-04 00:05
This is caused by a quirk of go, where if you are using a different geth version than coreth requires, it will attempt to build coreth with that same version. The interface of the database has changed from the version of geth that coreth uses, so that's what is causing this issue if you're using a newer version.

Coreth will be upgrading to use geth v1.10.2 soon, so this issue should be resolved by that change as well.

**Comment by aaronbuchwald** [comment] 2021-05-25 14:25
Closing since coreth has been updated to v1.10.2.

**Closed by aaronbuchwald** 2021-05-25 14:25 UTC
